/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D RECICLADO.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom006"].geometry}
          material={materials["TQ_ARD_front.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom006_1"].geometry}
          material={materials["TQ_ARD_back.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom006_2"].geometry}
          material={materials["TQ_ARD_edge.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D RECICLADO.gltf");
